name: SSH to MacOS VM (tmate Ultimate)

on: [workflow_dispatch]

jobs:
  ssh-mac:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Khởi tạo và Hiển thị Link SSH
      uses: mxschmitt/action-tmate@v3
      with:
        # Giữ máy ảo không bị ngắt kể cả khi bạn tắt tab trình duyệt
        detached: true
